### ISSUE TITLE
Ajout du shift+enter pour gérer les sauts de ligne

### ISSUE THREAD

**Issue by yohannpoli** [oltodo/hodorjs#46]
Analyser le comportement actuel et voir comment intégrer la feature.

Début de piste, il semblerait que les \n soit gérer comme une chaine de caractère(dont le length est = 1), il faut les compter dans le calcul de la position du focus (qui ne prend en compte que les textNode à l'heure actuel)

**Comment by lotholf** [comment]
Done #63
